version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongo
